<config.mk
#Load global variables
#
##Generate index for bam
results/%.bam.bai: data/%.bam
        set -x
        $SAMBAMBA index \
                --nthreads=$SAMBAMBA_THREADS \
                $prereq $target.build \
        && mv $target.build $target \
	&& ln -s "$(realpath $prereq)" "$(echo $target | sed -r -e 's#\.bai$##')"

# Remove previous output
clean:V:
        rm -r results

