<config.mk
# Load global variables, if applicable

# Generate global html report
results/%_fastqc.html:	data/%.fastq.gz
	DIR="`dirname $target`"
	mkdir -p "$DIR"
	$FASTQC $prereq -o "$DIR"

# Remove previous output
clean:V:
	rm -r results/*
