< ../../config.mk

QC:V:
	bin/targets | xargs mk

QC-results/%.ir.rtc.bam.QC:V: QC-results/%.ir.rtc.bam.flagstat_comparison.tsv
	set -x
	echo "QC report generated at $prereq"

QC-results/%.ir.rtc.bam.flagstat_comparison.tsv: QC-results/%.bam.flagstat QC-results/%.ir.rtc.bam.flagstat
	set -x
	echo "Number_of_reads\tRead_category\tFile" | cat - $prereq > $target.build \
	&& mv $target.build $target \
	&& rm $prereq

QC-results/%.ir.rtc.bam.flagstat: ../results/%.ir.rtc.bam
	set -x
	mkdir -p `dirname $target`
	java -jar $GATK \
		-T FlagStat \
		-R $REF \
		-I $prereq \
	| sed -e 's# #\t#' \
			-e 's# #_#g' \
	| awk -v BAMFILE=`basename $prereq` ' BEGIN {FS="\t"; OFS="\t"} {print $0,BAMFILE}' \
	> $target.build \
	&& mv $target.build $target

QC-results/%.bam.flagstat: ../data/%.bam
	set -x
	mkdir -p `dirname $target`
	java -jar $GATK \
		-T FlagStat \
		-R $REF \
		-I $prereq \
	| sed -e 's# #\t#' \
			-e 's# #_#g' \
	| awk -v BAMFILE=`basename $prereq` ' BEGIN {FS="\t"; OFS="\t"} {print $0,BAMFILE}' \
	> $target.build \
	&& mv $target.build $target