< ../config.mk
# Load Global variables for Variant Calling

# Generate recalibration table
results/%.recal-tab1:	data/%.ir.rtc.bam 
	set -x
	mkdir -p `dirname $target`
	java -jar $GATK \
		-T BaseRecalibrator \
		-R $REF \
		-I "data/"$stem".ir.rtc.bam" \
		-knownSites $dbSNP \
		-nct $NT \
		-L $coordenadas \
		-o $target".build" \
	&& mv $target".build" $target 

# Generate recalibrated bam files
results/%.recal1.bam: data/%.ir.rtc.bam results/%.recal-tab1 
	set -x
	java -jar $GATK \
		-T PrintReads \
		-R $REF \
		-I "data/"$stem".ir.rtc.bam" \
		-o $target".build" \
                -BQSR "results/"$stem".recal-tab1" \
		-nct $NT \
		-L $coordenadas \
	&& mv $target".build" $target \
        && mv $target".build.bai" $target".bai"

# Second run base recalibration
results/%.recal-tab2:        results/%.recal1.bam 
        set -x
        java -jar $GATK \
		-T BaseRecalibrator \
		-R $REF \
		-I "results/"$stem".recal1.bam" \
		-knownSites $dbSNP \
		-nct $NT \
		-L $coordenadas \
		-o $target".build" \
        && mv $target".build" $target

# Generate BQSR report
results/%.BQSR_plot.pdf:  results/%.recal-tab2 results/%.recal-tab1
	set -x
	java -jar $GATK \
		-T AnalyzeCovariates \
		-l DEBUG \
		-R $REF \
		-before "results/"$stem".recal-tab1" \
		-after "results/"$stem".recal-tab2" \
		-csv "results/"$stem".BQSR_plot.csv.build" \
		-plots $target".build" \
		-L $coordenadas \
 	&& mv $target".build" $target \
	&& mv "results/"$stem".BQSR_plot.csv.build" "results/"$stem".BQSR_plot.csv"

# Final second pass recalibrated bam file
results/%.recal2.bam: results/%.recal1.bam results/%.recal-tab2  results/%.BQSR_plot.pdf
        set -x
	mkdir -p `dirname $target`
        java -jar $GATK \
                -T PrintReads \
                -R $REF \
                -I "results/"$stem".recal1.bam" \
                -o $target".build" \
                -nct $NT \
                -BQSR "results/"$stem".recal-tab2" \
		-L $coordenadas \
        && mv $target".build" $target \
        && mv $target".build.bai" $target".bai" \
        && rm "results/"$stem".recal1.bam" \
	&& rm "results/"$stem".recal1.bam.bai" #\
#	&& rm "data/"$stem".markdup.ir.rtc.bam" #\
#	&& rm "data/"$stem".markdup.ir.rtc.bam.bai" #\
#	&& rm "data/"$stem".markdup.intervals"
