# Opciones generales de HTCondor.
universe = vanilla
#
initialdir = /labs/lf/tb/2-variantes/012-mk-gatk/1-H37Rv-analysis/003
should_transfer_files = NO
getenv = True
#
# Recursos necesarios para ejecutar el trabajo.
request_cpus = 3

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/46.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/46.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/46.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/46.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/35.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/35.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/35.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/35.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/50.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/50.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/50.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/50.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/23.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/23.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/23.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/23.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/12.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/12.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/12.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/12.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/28.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/28.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/28.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/28.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/39.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/39.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/39.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/39.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/24.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/24.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/24.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/24.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/57.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/57.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/57.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/57.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/32.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/32.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/32.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/32.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/41.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/41.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/41.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/41.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/52.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/52.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/52.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/52.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/21.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/21.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/21.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/21.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/48.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/48.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/48.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/48.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/30.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/30.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/30.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/30.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/43.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/43.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/43.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/43.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/26.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/26.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/26.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/26.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/55.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/55.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/55.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/55.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/49.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/49.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/49.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/49.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/31.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/31.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/31.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/31.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/42.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/42.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/42.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/42.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/27.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/27.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/27.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/27.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/54.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/54.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/54.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/54.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/53.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/53.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/53.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/53.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/45.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/45.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/45.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/45.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/36.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/36.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/36.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/36.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/58.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/58.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/58.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/58.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/02.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/02.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/02.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/02.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/25.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/25.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/25.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/25.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/56.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/56.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/56.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/56.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/33.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/33.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/33.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/33.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/47.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/47.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/47.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/47.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/34.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/34.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/34.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/34.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/51.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/51.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/51.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/51.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/22.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/22.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/22.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/22.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/29.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/29.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/29.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/29.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/05.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/05.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/05.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/05.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D12/13.g.vcf
output = results/diploide/MTC-D3-H37Rv-D12/13.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D12/13.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D12/13.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/48.g.vcf
output = results/diploide/Direct-H37Rv-D12/48.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/48.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/48.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/43.g.vcf
output = results/diploide/Direct-H37Rv-D12/43.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/43.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/43.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/30.g.vcf
output = results/diploide/Direct-H37Rv-D12/30.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/30.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/30.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/55.g.vcf
output = results/diploide/Direct-H37Rv-D12/55.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/55.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/55.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/26.g.vcf
output = results/diploide/Direct-H37Rv-D12/26.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/26.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/26.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/21.g.vcf
output = results/diploide/Direct-H37Rv-D12/21.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/21.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/21.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/52.g.vcf
output = results/diploide/Direct-H37Rv-D12/52.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/52.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/52.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/39.g.vcf
output = results/diploide/Direct-H37Rv-D12/39.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/39.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/39.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/57.g.vcf
output = results/diploide/Direct-H37Rv-D12/57.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/57.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/57.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/24.g.vcf
output = results/diploide/Direct-H37Rv-D12/24.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/24.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/24.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/41.g.vcf
output = results/diploide/Direct-H37Rv-D12/41.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/41.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/41.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/32.g.vcf
output = results/diploide/Direct-H37Rv-D12/32.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/32.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/32.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/35.g.vcf
output = results/diploide/Direct-H37Rv-D12/35.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/35.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/35.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/46.g.vcf
output = results/diploide/Direct-H37Rv-D12/46.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/46.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/46.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/23.g.vcf
output = results/diploide/Direct-H37Rv-D12/23.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/23.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/23.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/50.g.vcf
output = results/diploide/Direct-H37Rv-D12/50.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/50.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/50.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/28.g.vcf
output = results/diploide/Direct-H37Rv-D12/28.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/28.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/28.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/12.g.vcf
output = results/diploide/Direct-H37Rv-D12/12.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/12.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/12.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/34.g.vcf
output = results/diploide/Direct-H37Rv-D12/34.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/34.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/34.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/47.g.vcf
output = results/diploide/Direct-H37Rv-D12/47.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/47.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/47.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/22.g.vcf
output = results/diploide/Direct-H37Rv-D12/22.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/22.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/22.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/51.g.vcf
output = results/diploide/Direct-H37Rv-D12/51.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/51.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/51.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/05.g.vcf
output = results/diploide/Direct-H37Rv-D12/05.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/05.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/05.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/13.g.vcf
output = results/diploide/Direct-H37Rv-D12/13.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/13.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/13.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/29.g.vcf
output = results/diploide/Direct-H37Rv-D12/29.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/29.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/29.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/02.g.vcf
output = results/diploide/Direct-H37Rv-D12/02.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/02.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/02.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/56.g.vcf
output = results/diploide/Direct-H37Rv-D12/56.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/56.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/56.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/25.g.vcf
output = results/diploide/Direct-H37Rv-D12/25.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/25.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/25.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/33.g.vcf
output = results/diploide/Direct-H37Rv-D12/33.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/33.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/33.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/53.g.vcf
output = results/diploide/Direct-H37Rv-D12/53.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/53.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/53.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/36.g.vcf
output = results/diploide/Direct-H37Rv-D12/36.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/36.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/36.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/45.g.vcf
output = results/diploide/Direct-H37Rv-D12/45.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/45.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/45.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/58.g.vcf
output = results/diploide/Direct-H37Rv-D12/58.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/58.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/58.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/49.g.vcf
output = results/diploide/Direct-H37Rv-D12/49.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/49.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/49.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/42.g.vcf
output = results/diploide/Direct-H37Rv-D12/42.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/42.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/42.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/31.g.vcf
output = results/diploide/Direct-H37Rv-D12/31.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/31.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/31.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/54.g.vcf
output = results/diploide/Direct-H37Rv-D12/54.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/54.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/54.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D12/27.g.vcf
output = results/diploide/Direct-H37Rv-D12/27.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D12/27.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D12/27.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/34.g.vcf
output = results/diploide/Direct-H37Rv-D3/34.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/34.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/34.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/47.g.vcf
output = results/diploide/Direct-H37Rv-D3/47.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/47.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/47.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/22.g.vcf
output = results/diploide/Direct-H37Rv-D3/22.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/22.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/22.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/51.g.vcf
output = results/diploide/Direct-H37Rv-D3/51.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/51.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/51.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/29.g.vcf
output = results/diploide/Direct-H37Rv-D3/29.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/29.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/29.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/05.g.vcf
output = results/diploide/Direct-H37Rv-D3/05.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/05.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/05.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/13.g.vcf
output = results/diploide/Direct-H37Rv-D3/13.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/13.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/13.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/02.g.vcf
output = results/diploide/Direct-H37Rv-D3/02.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/02.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/02.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/56.g.vcf
output = results/diploide/Direct-H37Rv-D3/56.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/56.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/56.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/25.g.vcf
output = results/diploide/Direct-H37Rv-D3/25.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/25.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/25.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/33.g.vcf
output = results/diploide/Direct-H37Rv-D3/33.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/33.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/33.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/53.g.vcf
output = results/diploide/Direct-H37Rv-D3/53.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/53.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/53.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/36.g.vcf
output = results/diploide/Direct-H37Rv-D3/36.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/36.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/36.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/45.g.vcf
output = results/diploide/Direct-H37Rv-D3/45.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/45.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/45.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/58.g.vcf
output = results/diploide/Direct-H37Rv-D3/58.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/58.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/58.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/49.g.vcf
output = results/diploide/Direct-H37Rv-D3/49.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/49.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/49.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/42.g.vcf
output = results/diploide/Direct-H37Rv-D3/42.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/42.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/42.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/31.g.vcf
output = results/diploide/Direct-H37Rv-D3/31.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/31.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/31.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/54.g.vcf
output = results/diploide/Direct-H37Rv-D3/54.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/54.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/54.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/27.g.vcf
output = results/diploide/Direct-H37Rv-D3/27.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/27.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/27.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/48.g.vcf
output = results/diploide/Direct-H37Rv-D3/48.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/48.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/48.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/43.g.vcf
output = results/diploide/Direct-H37Rv-D3/43.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/43.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/43.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/30.g.vcf
output = results/diploide/Direct-H37Rv-D3/30.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/30.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/30.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/55.g.vcf
output = results/diploide/Direct-H37Rv-D3/55.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/55.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/55.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/26.g.vcf
output = results/diploide/Direct-H37Rv-D3/26.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/26.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/26.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/21.g.vcf
output = results/diploide/Direct-H37Rv-D3/21.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/21.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/21.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/52.g.vcf
output = results/diploide/Direct-H37Rv-D3/52.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/52.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/52.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/39.g.vcf
output = results/diploide/Direct-H37Rv-D3/39.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/39.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/39.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/57.g.vcf
output = results/diploide/Direct-H37Rv-D3/57.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/57.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/57.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/24.g.vcf
output = results/diploide/Direct-H37Rv-D3/24.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/24.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/24.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/41.g.vcf
output = results/diploide/Direct-H37Rv-D3/41.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/41.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/41.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/32.g.vcf
output = results/diploide/Direct-H37Rv-D3/32.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/32.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/32.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/35.g.vcf
output = results/diploide/Direct-H37Rv-D3/35.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/35.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/35.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/46.g.vcf
output = results/diploide/Direct-H37Rv-D3/46.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/46.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/46.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/23.g.vcf
output = results/diploide/Direct-H37Rv-D3/23.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/23.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/23.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/50.g.vcf
output = results/diploide/Direct-H37Rv-D3/50.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/50.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/50.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/12.g.vcf
output = results/diploide/Direct-H37Rv-D3/12.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/12.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/12.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/Direct-H37Rv-D3/28.g.vcf
output = results/diploide/Direct-H37Rv-D3/28.g.vcf.condor_out
log = results/diploide/Direct-H37Rv-D3/28.g.vcf.condor_log
error = results/diploide/Direct-H37Rv-D3/28.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/55.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/55.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/55.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/55.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/26.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/26.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/26.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/26.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/43.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/43.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/43.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/43.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/30.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/30.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/30.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/30.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/48.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/48.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/48.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/48.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/21.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/21.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/21.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/21.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/52.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/52.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/52.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/52.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/41.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/41.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/41.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/41.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/32.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/32.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/32.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/32.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/57.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/57.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/57.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/57.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/24.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/24.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/24.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/24.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/39.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/39.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/39.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/39.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/28.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/28.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/28.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/28.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/12.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/12.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/12.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/12.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/23.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/23.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/23.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/23.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/50.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/50.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/50.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/50.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/35.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/35.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/35.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/35.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/46.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/46.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/46.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/46.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/13.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/13.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/13.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/13.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/05.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/05.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/05.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/05.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/29.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/29.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/29.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/29.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/22.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/22.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/22.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/22.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/51.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/51.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/51.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/51.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/34.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/34.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/34.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/34.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/47.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/47.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/47.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/47.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/33.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/33.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/33.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/33.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/56.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/56.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/56.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/56.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/25.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/25.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/25.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/25.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/02.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/02.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/02.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/02.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/58.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/58.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/58.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/58.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/36.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/36.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/36.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/36.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/45.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/45.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/45.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/45.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/53.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/53.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/53.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/53.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/54.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/54.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/54.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/54.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/27.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/27.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/27.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/27.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/42.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/42.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/42.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/42.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/31.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/31.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/31.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/31.g.vcf.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/diploide/MTC-D3-H37Rv-D3/49.g.vcf
output = results/diploide/MTC-D3-H37Rv-D3/49.g.vcf.condor_out
log = results/diploide/MTC-D3-H37Rv-D3/49.g.vcf.condor_log
error = results/diploide/MTC-D3-H37Rv-D3/49.g.vcf.condor_err
queue
