< config.mk
# Load global variables if any
#
# Replace long to short CHR name.
#
results/%.hard_filtered.vcf:	data/%.hard_filtered.vcf
	mkdir -p "$(dirname "$target")"
	cat $prereq \
	| sed -r \
		-e 's#NC_000962.3_Mycobacterium_tuberculosis_H37Rv,_complete_genome#NC_000962.3#g' \
		-e 's#"NC_000962.3"#NC_000962.3#g' \
	> "$target"'.build' \
	&& mv "$target"'.build' "$target"

# Clean previous files
clean:V:
	bin/targets | xargs rm -f
