# Opciones generales de HTCondor.
universe = vanilla
#
initialdir = /labs/lf/tb/2-variantes/013-vcf-qc/analysis/001-missing-subject
should_transfer_files = NO
getenv = True
#
# Recursos necesarios para ejecutar el trabajo.
request_cpus = 1

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/1-H37Rv/diploide/filtrado/MTC-D3-H37Rv-D3/Llamado-conjunto_raw.PASS.tab
output = results/1-H37Rv/diploide/filtrado/MTC-D3-H37Rv-D3/Llamado-conjunto_raw.PASS.tab.condor_out
log = results/1-H37Rv/diploide/filtrado/MTC-D3-H37Rv-D3/Llamado-conjunto_raw.PASS.tab.condor_log
error = results/1-H37Rv/diploide/filtrado/MTC-D3-H37Rv-D3/Llamado-conjunto_raw.PASS.tab.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/1-H37Rv/diploide/filtrado/Direct-H37Rv-D3/Llamado-conjunto_raw.PASS.tab
output = results/1-H37Rv/diploide/filtrado/Direct-H37Rv-D3/Llamado-conjunto_raw.PASS.tab.condor_out
log = results/1-H37Rv/diploide/filtrado/Direct-H37Rv-D3/Llamado-conjunto_raw.PASS.tab.condor_log
error = results/1-H37Rv/diploide/filtrado/Direct-H37Rv-D3/Llamado-conjunto_raw.PASS.tab.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/1-H37Rv/diploide/filtrado/Direct-H37Rv-D12/Llamado-conjunto_raw.PASS.tab
output = results/1-H37Rv/diploide/filtrado/Direct-H37Rv-D12/Llamado-conjunto_raw.PASS.tab.condor_out
log = results/1-H37Rv/diploide/filtrado/Direct-H37Rv-D12/Llamado-conjunto_raw.PASS.tab.condor_log
error = results/1-H37Rv/diploide/filtrado/Direct-H37Rv-D12/Llamado-conjunto_raw.PASS.tab.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/1-H37Rv/diploide/filtrado/MTC-D3-H37Rv-D12/Llamado-conjunto_raw.PASS.tab
output = results/1-H37Rv/diploide/filtrado/MTC-D3-H37Rv-D12/Llamado-conjunto_raw.PASS.tab.condor_out
log = results/1-H37Rv/diploide/filtrado/MTC-D3-H37Rv-D12/Llamado-conjunto_raw.PASS.tab.condor_log
error = results/1-H37Rv/diploide/filtrado/MTC-D3-H37Rv-D12/Llamado-conjunto_raw.PASS.tab.condor_err
queue
