< config.mk

# Quality Control
# ===============
#
# Here you should describe why this is the correct qc for your analysis.
#
results/%:	data/%
	mkdir -p "$(dirname "$target")"
	# here goes your qc command
	> "$target"'.build' \
	&& mv "$target"'.build' "$target"
