< config.mk

#Filter only the annotated variants in TBDream
results/%-inTBDream.vcf:	data/after/%.vcf
	mkdir -p "$(dirname "$target")"
	bcftools filter \
		-e 'ID=="."' \
		$prereq \
	> "$target"'.build' \
	&& mv "$target"'.build' "$target"

#Count the number of annotated variants in TBDream
results/%.count:	results/%-inTBDream.vcf
	mkdir -p "$(dirname "$target")"
	bcftools view \
		-H \
		$prereq \
	| wc -l \
	> "$target"'.build' \
	&& mv "$target"'.build' "$target"

# Quality Control
# ===============
#
# Here you should describe why this is the correct qc for your analysis.
#
results/%:	data/%
	mkdir -p "$(dirname "$target")"
	# here goes your qc command
	> "$target"'.build' \
	&& mv "$target"'.build' "$target"
