#!/bin/sh

# For each file in `correct` directory:
#
#   - report which file is being checked.
#   - build the result using the mk module.
#   - compare the result with the correct reference.

bin/targets \
| sort \
| xargs \
	-I '{}' \
	sh -c "mk -a -f ../mkfile '{}' && diff \"$(echo {} | sed -re 's#^results/#correct/#')\" \"{}\""
