#!/bin/sh

# Execute all scripts named [number]_[something]_test
# in the expected numeric order.

find_tests() {
	find -name '*_test' \
	| sort -n
}

quote_everychar() {
	sed -r -e 's#(.)#\\\1#g'
}

main() {
	find_tests \
	| quote_everychar \
	| xargs -l ./log_test_results \
	| tee -a /dev/fd/2 \
	| grep -F '[err]' \
	>/dev/null \
	&& exit 1 \
	|| exit 0
}

main "$@"
