#!/bin/sh

# For each file in `error` directory:
#
#   - report which file is being checked.
#   - try to build the result using the mk module.
#   - the process must end with an error.

find -L error \
	-type f \
| sort \
| sed -r \
	\
| xargs \
	-I '{}' \
	mk -a -f ../mkfile '{}' \
&& {
	# FAIL: the process should fail.
	exit 1
} || {
	# correctly identified error.
	exit 0
}

